### ISSUE TITLE
PowerToys 0.75.0 初始化插件失败

### ISSUE THREAD

**Issue by Hyunicode** [N0I0C0K/PowerTranslator#21]
### log文件相关信息
```
[2023-10-31 10:29:01.1466] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::178]
Can't validate plugin ID of plugin <Translator> in D:\AppLocation\PowerToys\RunPlugins\Translator\Translator.dll: The static property <Main.PluginID> was not found.

[2023-10-31 10:29:01.1466] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::131]
Load cost for <Translator> is <18ms>

[2023-10-31 10:29:01.5289] [WARN] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::204]
Can not initialize Translator plugin as it was not loaded



[2023-10-31 10:29:01.9726] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\UWPApplication.cs::369]
-------------------------- Begin exception --------------------------
Message: 	Error status: KNOWN
		Program path: C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.9.3.0_x64__pcy8vm99wrpcg
		Exception thrown in called method: Not available
		Possible interpretation of the error: Load pri failed @{32669SamG.ModernFlyouts_0.9.3.0_x64__pcy8vm99wrpcg? ms-resource:Resources/ApplicationDescription} with HResult 2147942522 and location C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.9.3.0_x64__pcy8vm99wrpcg
		Possible resolution: Can be ignored and PowerToys Run should still continue, however the program may not be loaded

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : 未指定的错误

Exception stack trace:

Exception source     : 
Exception target site: 
Exception HResult    : -2147024774
-------------------------- End exception --------------------------


[2023-10-31 10:29:02.8068] [INFO] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::80]
Indexed 43 packaged applications

[2023-10-31 10:29:02.8068] [INFO] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::50]
Microsoft.Plugin.Program.Main - Package index cost <1279ms>

[2023-10-31 10:29:02.8068] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\UWPApplication.cs::632]
-------------------------- Begin exception --------------------------
Message: 	Error status: KNOWN
		Program path: C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe
		Exception thrown in called method: Not available
		Possible interpretation of the error: |Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge can't find logo uri for Assets\MicrosoftEdgeSquare44x44.png in package location: C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe
		Possible resolution: Can be ignored and PowerToys Run should still continue, however the program may not be loaded

Exception full name  : System.IO.FileNotFoundException
Exception message    : Unable to find the specified file.
Exception stack trace:

Exception source     : 
Exception target site: 
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2023-10-31 10:29:03.1302] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\ShellLinkHelper.cs::170]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\Windows\syswow64\odbcad32.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Microsoft.Plugin.Program.Programs.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Microsoft.Plugin.Program.Programs.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Microsoft.Plugin.Program
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------


[2023-10-31 10:29:03.1302] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\ShellLinkHelper.cs::170]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\PROGRA~2\WINDOW~4\wmplayer.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Microsoft.Plugin.Program.Programs.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Microsoft.Plugin.Program.Programs.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Microsoft.Plugin.Program
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------
```

### 如何触发
早上将PowerToys手动更新到0.75.0，再重新启动提示插件加载失败

![image](https://github.com/N0I0C0K/PowerTranslator/assets/81250265/28519392-8ce6-4dac-9a95-513b13057e73)
相同情况的还有另一个插件，我一共安装的两个额外插件都初始化失败了，逛了PowerToys的issues只发现这个比较相关[PowerToys29489](https://github.com/microsoft/PowerToys/issues/29489)

**Comment by N0I0C0K** [comment]
感谢。已经定位到问题是0.75版本将部分UI接口更改了，正在修复

**Comment by N0I0C0K** [comment]
修复完成，已发布release

**Comment by Hyunicode** [comment]
> 修复完成，已发布release

 感谢付出❤
